# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 819)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_13)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.target_date = QtWidgets.QDateEdit(self.groupBox_13)
        self.target_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 4)))
        self.target_date.setCalendarPopup(True)
        self.target_date.setTimeSpec(QtCore.Qt.LocalTime)
        self.target_date.setObjectName("target_date")
        self.verticalLayout_7.addWidget(self.target_date)
        self.verticalLayout_10.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_14)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.end_date = QtWidgets.QDateEdit(self.groupBox_14)
        self.end_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 4)))
        self.end_date.setCalendarPopup(True)
        self.end_date.setTimeSpec(QtCore.Qt.LocalTime)
        self.end_date.setObjectName("end_date")
        self.verticalLayout_8.addWidget(self.end_date)
        self.verticalLayout_10.addWidget(self.groupBox_14)
        self.verticalLayout_2.addWidget(self.groupBox_15)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.button_monthly_report_ref_last_year = QtWidgets.QRadioButton(self.groupBox_12)
        self.button_monthly_report_ref_last_year.setObjectName("button_monthly_report_ref_last_year")
        self.verticalLayout_9.addWidget(self.button_monthly_report_ref_last_year)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_9.addWidget(self.radioButton_2)
        self.verticalLayout_2.addWidget(self.groupBox_12)
        self.pushButton_weekly_update = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_weekly_update.setObjectName("pushButton_weekly_update")
        self.verticalLayout_2.addWidget(self.pushButton_weekly_update)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_WaferID_2 = QtWidgets.QRadioButton(self.groupBox_10)
        self.button_WaferID_2.setObjectName("button_WaferID_2")
        self.horizontalLayout_2.addWidget(self.button_WaferID_2)
        self.button_LotID_2 = QtWidgets.QRadioButton(self.groupBox_10)
        self.button_LotID_2.setObjectName("button_LotID_2")
        self.horizontalLayout_2.addWidget(self.button_LotID_2)
        self.gridLayout_3.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ignore_target_month = QtWidgets.QDateEdit(self.groupBox_11)
        self.ignore_target_month.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ignore_target_month.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.ignore_target_month.setCalendarPopup(True)
        self.ignore_target_month.setTimeSpec(QtCore.Qt.LocalTime)
        self.ignore_target_month.setObjectName("ignore_target_month")
        self.horizontalLayout_5.addWidget(self.ignore_target_month)
        self.gridLayout_3.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.columnstrTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox_9)
        self.columnstrTextEdit_2.setObjectName("columnstrTextEdit_2")
        self.gridLayout_3.addWidget(self.columnstrTextEdit_2, 1, 0, 1, 2)
        self.pushButton_ignore_monthly_report = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_ignore_monthly_report.setObjectName("pushButton_ignore_monthly_report")
        self.gridLayout_3.addWidget(self.pushButton_ignore_monthly_report, 2, 0, 1, 2)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.groupBox_9)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.query_func_comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.query_func_comboBox.setObjectName("query_func_comboBox")
        self.query_func_comboBox.addItem("")
        self.query_func_comboBox.addItem("")
        self.query_func_comboBox.addItem("")
        self.query_func_comboBox.addItem("")
        self.query_func_comboBox.addItem("")
        self.query_func_comboBox.addItem("")
        self.query_func_comboBox.addItem("")
        self.query_func_comboBox.addItem("")
        self.query_func_comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.query_func_comboBox)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_First_5 = QtWidgets.QRadioButton(self.groupBox_7)
        self.button_First_5.setObjectName("button_First_5")
        self.verticalLayout_4.addWidget(self.button_First_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_Final_yield = QtWidgets.QRadioButton(self.groupBox_8)
        self.button_Final_yield.setObjectName("button_Final_yield")
        self.verticalLayout_5.addWidget(self.button_Final_yield)
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_WaferID = QtWidgets.QRadioButton(self.groupBox_4)
        self.button_WaferID.setObjectName("button_WaferID")
        self.horizontalLayout.addWidget(self.button_WaferID)
        self.button_LotID = QtWidgets.QRadioButton(self.groupBox_4)
        self.button_LotID.setObjectName("button_LotID")
        self.horizontalLayout.addWidget(self.button_LotID)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.pushButton_query_lot = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_query_lot.setObjectName("pushButton_query_lot")
        self.gridLayout_4.addWidget(self.pushButton_query_lot, 2, 0, 1, 1)
        self.columnstrTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.columnstrTextEdit.setObjectName("columnstrTextEdit")
        self.gridLayout_4.addWidget(self.columnstrTextEdit, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lineEdit_Description_2 = QtWidgets.QLineEdit(self.groupBox_20)
        self.lineEdit_Description_2.setObjectName("lineEdit_Description_2")
        self.verticalLayout_15.addWidget(self.lineEdit_Description_2)
        self.verticalLayout_11.addWidget(self.groupBox_20)
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lineEdit_Description = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_Description.setObjectName("lineEdit_Description")
        self.verticalLayout_13.addWidget(self.lineEdit_Description)
        self.verticalLayout_11.addWidget(self.groupBox_18)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lineEdit_2_Capability = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEdit_2_Capability.setObjectName("lineEdit_2_Capability")
        self.verticalLayout_12.addWidget(self.lineEdit_2_Capability)
        self.verticalLayout_11.addWidget(self.groupBox_19)
        self.pushButton_query_recipe_by_des_and_cap = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_query_recipe_by_des_and_cap.setObjectName("pushButton_query_recipe_by_des_and_cap")
        self.verticalLayout_11.addWidget(self.pushButton_query_recipe_by_des_and_cap)
        self.horizontalLayout_6.addWidget(self.groupBox_16)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.console_output = QtWidgets.QTextEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_output.sizePolicy().hasHeightForWidth())
        self.console_output.setSizePolicy(sizePolicy)
        self.console_output.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.console_output.setReadOnly(True)
        self.console_output.setObjectName("console_output")
        self.gridLayout_2.addWidget(self.console_output, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 21))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuUpdate_file = QtWidgets.QMenu(self.menuOption)
        self.menuUpdate_file.setObjectName("menuUpdate_file")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuConvert_jpg_to_png = QtWidgets.QMenu(self.menubar)
        self.menuConvert_jpg_to_png.setObjectName("menuConvert_jpg_to_png")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDefect_code_lists_by_Inspection_ini = QtWidgets.QAction(MainWindow)
        self.actionDefect_code_lists_by_Inspection_ini.setObjectName("actionDefect_code_lists_by_Inspection_ini")
        self.actionDefect_code_lists_by_database = QtWidgets.QAction(MainWindow)
        self.actionDefect_code_lists_by_database.setObjectName("actionDefect_code_lists_by_database")
        self.actionDefectGroup_by_EDAS_ini = QtWidgets.QAction(MainWindow)
        self.actionDefectGroup_by_EDAS_ini.setObjectName("actionDefectGroup_by_EDAS_ini")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionocap = QtWidgets.QAction(MainWindow)
        self.actionocap.setObjectName("actionocap")
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.menuUpdate_file.menuAction())
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionSettings)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuConvert_jpg_to_png.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ReportGenerator_ver _1.0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Query data from target date\'s week to end date\'s week"))
        self.label_3.setText(_translate("MainWindow", "Select target date"))
        self.label_8.setText(_translate("MainWindow", "Select end date"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Reference for the differences of monthly report"))
        self.button_monthly_report_ref_last_year.setText(_translate("MainWindow", "Whole of last year"))
        self.radioButton_2.setText(_translate("MainWindow", "Last month"))
        self.pushButton_weekly_update.setText(_translate("MainWindow", "Start"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Ignored lots or wafers"))
        self.button_WaferID_2.setText(_translate("MainWindow", "WaferID"))
        self.button_LotID_2.setText(_translate("MainWindow", "LotID"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Target month"))
        self.ignore_target_month.setDisplayFormat(_translate("MainWindow", "yyyy/M"))
        self.pushButton_ignore_monthly_report.setText(_translate("MainWindow", "Generate modified monthly report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Weekly_update"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Check list"))
        self.label_5.setText(_translate("MainWindow", "Query function:"))
        self.query_func_comboBox.setItemText(0, _translate("MainWindow", "summary data"))
        self.query_func_comboBox.setItemText(1, _translate("MainWindow", "wafers history search"))
        self.query_func_comboBox.setItemText(2, _translate("MainWindow", "lots history search"))
        self.query_func_comboBox.setItemText(3, _translate("MainWindow", "inspection wafer map(s)"))
        self.query_func_comboBox.setItemText(4, _translate("MainWindow", "stacked wafer maps (multiple)"))
        self.query_func_comboBox.setItemText(5, _translate("MainWindow", "cp value wafer map(s)"))
        self.query_func_comboBox.setItemText(6, _translate("MainWindow", "lot wafer part information"))
        self.query_func_comboBox.setItemText(7, _translate("MainWindow", "max defect count"))
        self.query_func_comboBox.setItemText(8, _translate("MainWindow", "cp reverse bias updated map"))
        self.button_First_5.setText(_translate("MainWindow", "First 5 character"))
        self.label_6.setText(_translate("MainWindow", "      only take first 5 character as part name"))
        self.button_Final_yield.setText(_translate("MainWindow", "Final yield"))
        self.label_7.setText(_translate("MainWindow", "      only take lot that pass stage:\n"
"      (請輸入FINAL YIELD PASS DIE)"))
        self.groupBox.setTitle(_translate("MainWindow", "Input lots or wafers"))
        self.button_WaferID.setText(_translate("MainWindow", "WaferID"))
        self.button_LotID.setText(_translate("MainWindow", "LotID"))
        self.pushButton_query_lot.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Query_lot_information"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Search recipe by process description and capability"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Recipe tilte ..."))
        self.groupBox_18.setTitle(_translate("MainWindow", "Process hint, PPID ..."))
        self.groupBox_19.setTitle(_translate("MainWindow", "Capability"))
        self.pushButton_query_recipe_by_des_and_cap.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Recipe_information"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Console information"))
        self.menuOption.setTitle(_translate("MainWindow", "File"))
        self.menuUpdate_file.setTitle(_translate("MainWindow", "Update file"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuConvert_jpg_to_png.setTitle(_translate("MainWindow", "Convert jpg to png"))
        self.actionDefect_code_lists_by_Inspection_ini.setText(_translate("MainWindow", "Defect code lists by Inspection.ini"))
        self.actionDefect_code_lists_by_database.setText(_translate("MainWindow", "Defect code lists by database"))
        self.actionDefectGroup_by_EDAS_ini.setText(_translate("MainWindow", "DefectGroup by EDAS.ini"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionocap.setText(_translate("MainWindow", "OCAP_template"))

